// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpFyQgtZlYULwfsuwd_jrN4UTsx5Ye5Y',
    appId: '1:682953698687:web:fe838ba6d3a6039372be4a',
    messagingSenderId: '682953698687',
    projectId: 'e-commerce-833c2',
    authDomain: 'e-commerce-833c2.firebaseapp.com',
    storageBucket: 'e-commerce-833c2.appspot.com',
    measurementId: 'G-EF0PS3VH0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9End5ZgWPqGz9xoV4WfW6GWRHvL6wHUw',
    appId: '1:682953698687:android:07a15b4e89cdd4c872be4a',
    messagingSenderId: '682953698687',
    projectId: 'e-commerce-833c2',
    storageBucket: 'e-commerce-833c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDspTKmbnrJ9K2iMcju9NKs1qnKGBr3Gm0',
    appId: '1:682953698687:ios:356f7928a23ce14672be4a',
    messagingSenderId: '682953698687',
    projectId: 'e-commerce-833c2',
    storageBucket: 'e-commerce-833c2.appspot.com',
    iosClientId: '682953698687-6u7mb9n1mpq9so09e7rovgak98m61q29.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDspTKmbnrJ9K2iMcju9NKs1qnKGBr3Gm0',
    appId: '1:682953698687:ios:356f7928a23ce14672be4a',
    messagingSenderId: '682953698687',
    projectId: 'e-commerce-833c2',
    storageBucket: 'e-commerce-833c2.appspot.com',
    iosClientId: '682953698687-6u7mb9n1mpq9so09e7rovgak98m61q29.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
